export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const INCREMENT_ENTHUSIASM_REQUESTED = 'INCREMENT_ENTHUSIASM_REQUESTED';
export type INCREMENT_ENTHUSIASM_REQUESTED = typeof INCREMENT_ENTHUSIASM_REQUESTED;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
